services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
      - "3000:3000"
    volumes:
      - .:/var/www
      - /var/www/spa/node_modules
      - /var/www/vendor

